# Name of this GitHub Actions workflow.
name: Semgrep Scan

on:
  # Scan changed files in PRs (diff-aware scanning):
  pull_request:
    branches:
      - main
  # Scan on-demand through GitHub Actions interface:
  workflow_dispatch: {}
  # Scan mainline branches if there are changes to .github/workflows/semgrep.yml:
  push:
    branches:
      - main
      - master
    paths:
      - .github/workflows/semgrep.yml
  # Schedule the CI job (this method uses cron syntax):
  schedule:
    - cron: '20 17 * * *' # Sets Semgrep to scan every day at 17:20 UTC.
    # It is recommended to change the schedule to a random time.

jobs:
  semgrep:
    # User definable name of this GitHub Actions job.
    name: semgrep/ci
    # If you are self-hosting, change the following `runs-on` value:
    runs-on: ubuntu-latest

    steps:
      # Checkout project source with GitHub Actions Checkout.
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: main
          fetch-depth: 0  # Ensure the full history is fetched for diff-aware scanning

      # Checkout rules from another repository.
      - name: Checkout rules
        uses: actions/checkout@v4
        with:
          repository: tembalii/rule-reg
          path: rules

      # List files in the rules directory for debugging.
      - name: List rules directory
        run: ls -R rules

      # Set up Python.
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install Semgrep.
      - name: Install Semgrep
        run: pip install semgrep

      # Ensure the repository is correctly checked out.
      - name: Verify Git Repository
        run: |
          cd main
          git status

      # Get the list of changed files.
      - name: Get changed files
        id: changed-files
        run: |
          cd main
          git fetch origin main
          git diff --name-only origin/main...HEAD > changed_files.txt

      # Run Semgrep scan on changed files.
      - name: Run Semgrep Scan
        run: |
          cd main
          if [ -s changed_files.txt ]; then
            semgrep scan --config=https://raw.githubusercontent.com/tembalii/rule-reg/main/rules/rule1.yaml --config=https://raw.githubusercontent.com/tembalii/rule-reg/main/rules/rule2.yaml $(cat changed_files.txt)
          else
            echo "No changed files to scan."
          fi
        env:
          # Connect to Semgrep AppSec Platform through your SEMGREP_APP_TOKEN.
          # Generate a token from Semgrep AppSec Platform > Settings
          # and add it to your GitHub secrets.
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

    # Skip any PR created by dependabot to avoid permission issues:
    if: github.actor != 'dependabot[bot]'
