# Name of this GitHub Actions workflow.
name: Semgrep CI

on:
  # Trigger scanning for pull requests to main branch.
  pull_request:
    branches:
      - main
  # Allow manual triggering of the workflow.
  workflow_dispatch: {}
  # Scan mainline branches if changes are made to the workflow configuration file.
  push:
    branches:
      - main
      - master
    paths:
      - .github/workflows/semgrep.yml
  # Schedule daily scans at 17:20 UTC.
  schedule:
    - cron: '20 17 * * *'

jobs:
  semgrep:
    # User definable name of this GitHub Actions job.
    name: semgrep/ci
    runs-on: ubuntu-latest
    # container:
    #   image: semgrep/semgrep
      
    # Skip any PR created by dependabot to avoid permission issues:
    if: (github.actor != 'dependabot[bot]')

    steps:
      # Fetch the project source.
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure the full history is fetched for diff-aware scanning

      # Checkout rules from a specific repository.
      - name: Checkout rules
        uses: actions/checkout@v3
        with:
          repository: tembalii/rule-reg
          path: rules

      # Set up Python environment.
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install Semgrep.
      - name: Install Semgrep
        run: pip install semgrep

      # Run Semgrep CI with the specified rules configuration.
      - name: Run Semgrep CI
        run: semgrep ci --config=rules/rule1.yaml
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
